In [24]:
import numpy as np
import pandas as pd

In [11]:
#1) Generate an array of zeroes using inbuilt numpy function.

arr= np.zeros((3,3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#2) Run the given code and find the dot product of both arrays.
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[5 9 4 5]
 [3 9 3 7]
 [3 2 4 5]]
[[7 4 5]
 [5 8 9]
 [9 6 4]
 [5 8 2]]


In [13]:
a.dot(b)

array([[141, 156, 132],
       [128, 158, 122],
       [ 92,  92,  59]])

In [16]:
print (np.dot(a,b))

[[141 156 132]
 [128 158 122]
 [ 92  92  59]]


In [ ]:
#3)Read the csv file provided using pandas and display the first 5 entries

In [57]:
data = pd.read_csv("data_ass.csv")
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

In [58]:
#4)Describe the data with all features.
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [59]:
#5)Find the total count of missing values for each feature.
data.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [60]:
#6)Display all the unique values from the 'DESCRIPTION’ column.
data['DESCRIPTION'].unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [61]:
#7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.
data.groupby('DESCRIPTION').mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [62]:
#8)Generate a random sample of 10 rows from the data.
data.sample(n=10)



OBJECTID                             UNIT_NAME            DESCRIPTION  \
12        35  Butte St. Paul State Recreation Area  State Recreation Area   
16        37            Elkhorn State Natural Area     State Natural Area   
1         22                Beaver Lake State Park             State Park   
10        31            Little Missouri State Park             State Park   
15        34             Lake Sakakawea State Park             State Park   
0         21             Fort Stevenson State Park             State Park   
23        45                Cross Ranch State Park             State Park   
14        33               Turtle River State Park             State Park   
18        39       Gunlogson State Nature Preserve  State Nature Preserve   
6         27             Lake Metigoshe State Park             State Park   

      ACRES  SHAPE.AREA  SHAPE.LEN  
12    51.23    0.000025   0.022095  
16   264.84    0.000127   0.067082  
1    273.16    0.000129   0.080067  
10  6492.93    0.003136   0.313756  
15   739.52    0.000357   0.191806  
0    586.48    0.000284   0.135641  
23   569.07    0.000274   0.180257  
14   775.28    0.000378   0.145220  
18    95.89    0.000048   0.040465  
6   1508.53    0.000751   0.212196

In [90]:
#9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

data['New_feature']= np.random.rand(25,1) 
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  New_feature  
0              State Park   586.48    0.000284   0.135641     0.430451  
1              State Park   273.16    0.000129   0.080067     0.293093  
2              State Park   836.47    0.000399   0.119868     0.575938  
3              State Park   933.78    0.000444   0.128733     0.489548  
4              State Park   959.33    0.000469   0.125546     0.607451  
5              State Park   930.30    0.000461   0.166712     0.241366  
6              State Park  1508.53    0.000751   0.212196     0.413119  
7              State Park   524.81    0.000256   0.130420     0.461828  
8     Interpretive Center    14.71    0.000007   0.016774     0.822885  
9   State Recreation Area    11.40    0.000005   0.009396     0.007211  
10             State Park  6492.93    0.003136   0.313756     0.731390  
11             State Park    63.03    0.000030   0.024016     0.210149  
12  State Recreation Area    51.23    0.000025   0.022095     0.064918  
13  State Recreation Area   247.11    0.000120   0.050518     0.684469  
14             State Park   775.28    0.000378   0.145220     0.514535  
15             State Park   739.52    0.000357   0.191806     0.913126  
16     State Natural Area   264.84    0.000127   0.067082     0.995534  
17  State Recreation Area    21.56    0.000010   0.013294     0.074565  
18  State Nature Preserve    95.89    0.000048   0.040465     0.863229  
19  State Nature Preserve    72.30    0.000034   0.033885     0.155776  
20     State Natural Area   174.39    0.000083   0.087192     0.564521  
21  State Recreation Area  1236.98    0.000615   0.338800     0.523901  
22  State Recreation Area   695.04    0.000345   0.086487     0.403931  
23             State Park   569.07    0.000274   0.180257     0.647606  
24  State Recreation Area    25.22    0.000013   0.026357     0.605913

In [88]:
#10) Replace zero value of column 'OBJECTID' with mean value permanently.
mean_o= data.OBJECTID.mean()
mean_o
data.OBJECTID.replace(0,mean_o,inplace = True)



In [72]:
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  
0              State Park   586.48    0.000284   0.135641  
1              State Park   273.16    0.000129   0.080067  
2              State Park   836.47    0.000399   0.119868  
3              State Park   933.78    0.000444   0.128733  
4              State Park   959.33    0.000469   0.125546  
5              State Park   930.30    0.000461   0.166712  
6              State Park  1508.53    0.000751   0.212196  
7              State Park   524.81    0.000256   0.130420  
8     Interpretive Center    14.71    0.000007   0.016774  
9   State Recreation Area    11.40    0.000005   0.009396  
10             State Park  6492.93    0.003136   0.313756  
11             State Park    63.03    0.000030   0.024016  
12  State Recreation Area    51.23    0.000025   0.022095  
13  State Recreation Area   247.11    0.000120   0.050518  
14             State Park   775.28    0.000378   0.145220  
15             State Park   739.52    0.000357   0.191806  
16     State Natural Area   264.84    0.000127   0.067082  
17  State Recreation Area    21.56    0.000010   0.013294  
18  State Nature Preserve    95.89    0.000048   0.040465  
19  State Nature Preserve    72.30    0.000034   0.033885  
20     State Natural Area   174.39    0.000083   0.087192  
21  State Recreation Area  1236.98    0.000615   0.338800  
22  State Recreation Area   695.04    0.000345   0.086487  
23             State Park   569.07    0.000274   0.180257  
24  State Recreation Area    25.22    0.000013   0.026357